# -*- coding: utf-8 -*-

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#                      Python Adventure Writing System                          #
#                        Tkinter Terminal Support Code                          #
#                     Originally Written by Roger Plowman (c) 2008             #
#                     Converted to Tkinter by Adam, 2026                        #
#                                                                               #
# The C="""...""" statements scattered throughout this source code are actually #
# a work-around for Python's lack of block comments. Notobot++ can only fold    #
# block comments, not a series of comment lines. Using C="""...""" doesn't      #
# increase PAWS memory footprint, although it does have a tiny impact           #
# on loading time.                                                              #
#                                                                               #
C="""
  This module contains the bulk of the terminal program. It was originally
  generated by the Boa Constructor IDE for wxPython. It has been rewritten
  to use Tkinter (Python's standard GUI library) so that the game can run
  without requiring wxPython to be installed.

  Written By: Roger Plowman (original), Adam (Tkinter port)
  Written On: 01/20/2008 (original), 2026 (Tkinter port)
  """
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#********************************************************************************
#                                 Library Imports
#

import tkinter as tk
from tkinter import filedialog, messagebox, font as tkfont

from .Core import *
from .Universe import *

def create(parent):
    return TFrame()


class TFrame(tk.Tk):
    """
    PAWS Terminal Frame — Tkinter implementation.

    This class creates the main window with a text display area, a command
    input field, a status bar, and a menu bar. It replaces the original
    wxPython implementation while preserving the same interface that Core.py's
    ClassTerminal expects (TDisplay, TInput, TStatusBar, etc.).
    """

    def __init__(self):
        """Initialize Terminal."""
        super().__init__()

        self.title("PAWS Terminal")
        self.geometry("829x786")

        #------------------------------
        # Create Menu Bar
        #------------------------------

        self._create_menu()

        #------------------------------
        # Create Status Bar
        #------------------------------

        self.TStatusBar = tk.Label(self, text="Status Bar Info Goes Here",
                                   bd=1, relief=tk.SUNKEN, anchor=tk.W,
                                   font=("Courier New", 12, "bold"))
        self.TStatusBar.pack(side=tk.BOTTOM, fill=tk.X)

        #------------------------------
        # Create Input Field
        #------------------------------

        self.TInput = tk.Entry(self, font=("Courier", 12, "bold"))
        self.TInput.pack(side=tk.BOTTOM, fill=tk.X)
        self.TInput.bind("<Return>", self.OnTInputTextEnter)
        self.TInput.config(state=tk.DISABLED)

        #------------------------------
        # Create Text Display
        #------------------------------

        # The text display is the main area where game output appears.
        # We use a tk.Text widget with word wrap and a "default" tag
        # for the initial styling.

        self.TDisplay = tk.Text(self, wrap=tk.WORD, font=("Arial", 12),
                                padx=5, pady=5)
        self.TDisplay.pack(fill=tk.BOTH, expand=True)
        self.TDisplay.config(state=tk.DISABLED)

        # Configure the default tag for normal text style
        self.TDisplay.tag_configure("default",
                                     font=("Arial", 12),
                                     foreground="white",
                                     background="black")

        # Insert initial message and disable editing
        self.TDisplay.config(state=tk.NORMAL)
        self.TDisplay.insert(tk.END,
            "To run a game, choose File \u2192 Pick Game \u2026 "
            "then choose a game from the list.", "default")
        self.TDisplay.config(state=tk.DISABLED)

        #------------------------------
        # Disable Unusable Menu Items
        #------------------------------

        # The following menu items can't be used until a game is selected
        # and running. The default for Tkinter menu items is enabled, so we
        # have to disable them before the menu can be used.

        self._set_menu_state("disabled")

    #********************************************************************************
    #                              Menu Creation
    #

    def _create_menu(self):
        """Create the menu bar with File, View, and Help menus."""

        menu_bar = tk.Menu(self)

        #--- File Menu ---

        file_menu = tk.Menu(menu_bar, tearoff=0)

        file_menu.add_command(label="Pick Game \u2026",
                              command=self.OnMenuFilePlaygameMenu)
        file_menu.add_separator()
        file_menu.add_command(label="Save",
                              command=self.OnMenuFileSaveMenu)
        file_menu.add_command(label="Restore",
                              command=self.OnMenuFileItems2Menu)
        file_menu.add_separator()
        file_menu.add_command(label="Debug",
                              command=self.OnMenuFileDebugMenu)
        file_menu.add_command(label="Log Game",
                              command=self.OnMenuFileLoggameMenu)
        file_menu.add_separator()
        file_menu.add_command(label="Verbose",
                              command=self.OnMenuFileVerboseMenu)
        file_menu.add_command(label="Terse",
                              command=self.OnMenuFileTerseMenu)
        file_menu.add_separator()
        file_menu.add_command(label="Exit",
                              command=self.OnMenuFileExitMenu)

        menu_bar.add_cascade(label="File", menu=file_menu)

        #--- View Menu ---

        view_menu = tk.Menu(menu_bar, tearoff=0)

        view_menu.add_command(label="Font \u2026",
                              command=self.OnMenuViewFontMenu)

        menu_bar.add_cascade(label="View", menu=view_menu)

        #--- Help Menu ---

        help_menu = tk.Menu(menu_bar, tearoff=0)

        help_menu.add_command(label="Hints",
                              command=self.OnMenuHelpHintsMenu)
        help_menu.add_command(label="About PAWS",
                              command=self.OnMenuHelpAboutMenu)

        menu_bar.add_cascade(label="Help", menu=help_menu)

        self.config(menu=menu_bar)

        # Store references so we can enable/disable items later
        self._menu_bar = menu_bar
        self._file_menu = file_menu
        self._view_menu = view_menu
        self._help_menu = help_menu

    def _set_menu_state(self, state):
        """
        Enable or disable the menu items that require a running game.

        state should be "disabled" (before game load) or "normal" (after
        game load). The Pick Game entry gets the opposite state.
        """
        # Pick Game is always available before a game, disabled after
        pick_state = "normal" if state == "disabled" else "disabled"

        # File menu: indices (0-based with separators)
        # 0 = Pick Game
        # 1 = separator
        # 2 = Save
        # 3 = Restore
        # 4 = separator
        # 5 = Debug
        # 6 = Log Game
        # 7 = separator
        # 8 = Verbose
        # 9 = Terse
        # 10 = separator
        # 11 = Exit

        self._file_menu.entryconfig(0, state=pick_state)    # Pick Game
        self._file_menu.entryconfig(2, state=state)          # Save
        self._file_menu.entryconfig(3, state=state)          # Restore
        self._file_menu.entryconfig(5, state=state)          # Debug
        self._file_menu.entryconfig(6, state=state)          # Log Game
        self._file_menu.entryconfig(8, state=state)          # Verbose
        self._file_menu.entryconfig(9, state=state)          # Terse

        # View menu
        self._view_menu.entryconfig(0, state=state)          # Font

        # Help menu
        self._help_menu.entryconfig(0, state=state)          # Hints

    #********************************************************************************
    #                              Menu Handlers
    #

    def OnMenuFileSaveMenu(self):
        """
        This function is run when Save is clicked on the menu. All it does
        is call the terminal's Feed function to emulate the player typing
        a command.
        """
        Terminal.Feed("save")

    def OnMenuFileItems2Menu(self):
        """
        This function is run when Restore is clicked on the menu. All it does
        is call the terminal's Feed function to emulate the player typing
        a command.
        """
        Terminal.Feed("restore")

    def OnMenuFileDebugMenu(self):
        """
        This function is run when Debug is clicked on the menu. All it does
        is call the terminal's Feed function to emulate the player typing
        a command.
        """
        Terminal.Feed("debug")

    def OnMenuFileLoggameMenu(self):
        """
        This function is run when Log Game is clicked on the menu. All it
        does is call the terminal's Feed function to emulate the player
        typing a command.
        """
        Terminal.Feed("transcribe")

    def OnMenuFileVerboseMenu(self):
        """
        This function is run when Verbose is clicked on the menu. All it
        does is call the terminal's Feed function to emulate the player
        typing a command.
        """
        Terminal.Feed("verbose")

    def OnMenuFileTerseMenu(self):
        """
        This function is run when Terse is clicked on the menu. All it does
        is call the terminal's Feed function to emulate the player typing
        a command.
        """
        Terminal.Feed("terse")

    def OnMenuFileExitMenu(self):
        """
        This function is run when Exit is clicked on the menu. All it does
        is close the terminal frame (the window holding the terminal).
        """
        self.destroy()

    def OnMenuHelpHintsMenu(self):
        """
        This function is run when "Hints" is clicked on the menu. All it
        does is call the terminal's Feed function to emulate the player
        typing a command.
        """
        Terminal.Feed("help")

    def OnMenuHelpAboutMenu(self):
        """
        This function is run when About is clicked on the menu. It shows
        an About dialog.
        """
        description = (
            "Core Engine: v" + Engine.Version + ", "
            "Universe: v" + UniverseVersion + "\n\n"
            "PAWS is the Python Adventure Writing System, "
            "a software to play and develop Interactive Fiction with. "
            "It was originally developed by Roger Plowman and continued "
            "in 2016 by Matthias C. Hormann, just for the fun of it.\n\n"
            "https://github.com/Moonbase59/PAWS\n\n"
            "Developers:\n"
            "  Roger Plowman\n"
            "  Kevin Russell\n"
            "  Matthias C. Hormann"
        )
        messagebox.showinfo("About PAWS", description)

    def OnTInputTextEnter(self, event=None):
        """
        This function is run when the player presses Enter after typing a
        command.
        """

        #-----------------------------
        # If Player JUST pressed Enter
        #-----------------------------

        # If the player hit the Enter key without typing a command we return
        # immediately. This allows the player to type another command.

        if not len(self.TInput.get()):
            return

        #-----------------------
        # Process Player's Input
        #-----------------------

        self.ProcessPlayerInput()

    def OnMenuFilePlaygameMenu(self):
        """
        This function is run when Play Game is clicked on the menu.
        """

        #------------------------------
        # Hook Frame into Core Terminal
        #------------------------------

        Terminal.Frame = self

        #----------------------
        # Ready The File Dialog
        #----------------------

        filename = filedialog.askopenfilename(
            title="Choose a game",
            initialdir=".",
            filetypes=[("PAWS Games (*.py)", "*.py"), ("All files", "*.*")]
        )

        # If the player clicked Cancel or didn't select a file, exit.
        if not filename:
            return

        #-------------------------
        # Retrieve the Game's Name
        #-------------------------

        # We need just the filename without path and without the .py extension.
        import os
        basename = os.path.basename(filename)
        Global.GameModule = basename[:-3]  # Strip .py extension

        if Global.GameModule == "LoadTerminal":
            self.TDisplay.config(state=tk.NORMAL)
            self.TDisplay.delete("1.0", tk.END)
            self.TDisplay.config(state=tk.DISABLED)
            Say("~p ~p ~p ~title ~lrd ~b LoadTerminal ~l is not a game.")
            return

        #------------------
        # Enable Menu Items
        #------------------

        self._set_menu_state("normal")

        #---------------------------------
        # Enable The Player's Command Box
        #---------------------------------

        self.TInput.config(state=tk.NORMAL)
        self.TInput.delete(0, tk.END)
        self.TInput.focus_set()

        # Set the default font for Terminal
        Terminal.CurrentFont = ("Arial", 12)

        #------------
        # Import Game
        #------------

        STMT = "from %s import *" % Global.GameModule
        exec(STMT, globals())

        #-------------------
        # Start Running Game
        #-------------------

        Engine.SetUpGame()
        Global.GameState = RUNNING
        Say("~p " + P.AP().Prompt())

    def OnMenuViewFontMenu(self, event=None):
        """
        Change the font used in the terminal. Called when Font... menu is
        clicked.

        Note: Tkinter does not have a built-in font dialog like wxPython's
        wx.FontDialog. This implementation provides a simple font selection
        dialog that lets the user choose font family and size.
        """

        #------------------------------
        # Hook Frame into Core Terminal
        #------------------------------

        Terminal.Frame = self

        #------------------------------
        # Simple Font Selection Dialog
        #------------------------------

        # Create a simple toplevel dialog for font selection
        font_dialog = tk.Toplevel(self)
        font_dialog.title("Select Font")
        font_dialog.geometry("300x350")
        font_dialog.transient(self)
        font_dialog.grab_set()

        # Get available font families
        available_families = sorted(tkfont.families(self))

        # Font family listbox
        tk.Label(font_dialog, text="Font Family:").pack(anchor=tk.W, padx=5)
        family_var = tk.StringVar(value="Arial")
        family_listbox = tk.Listbox(font_dialog, listvariable=family_var,
                                     height=10, exportselection=False)
        family_listbox.pack(fill=tk.BOTH, expand=True, padx=5)

        # Populate the listbox
        for family in available_families:
            family_listbox.insert(tk.END, family)

        # Set initial selection to current font family
        current_family = Terminal.CurrentFont[0] if Terminal.CurrentFont else "Arial"
        try:
            idx = available_families.index(current_family)
            family_listbox.selection_set(idx)
            family_listbox.see(idx)
        except ValueError:
            family_listbox.selection_set(0)

        # Font size spinbox
        tk.Label(font_dialog, text="Font Size:").pack(anchor=tk.W, padx=5, pady=(10, 0))
        size_var = tk.IntVar(value=Terminal.CurrentFontPitch)
        size_spinbox = tk.Spinbox(font_dialog, from_=8, to=36,
                                   textvariable=size_var, width=5)
        size_spinbox.pack(anchor=tk.W, padx=5)

        def apply_font():
            """Apply the selected font and close the dialog."""
            selection = family_listbox.curselection()
            if not selection:
                return

            chosen_family = available_families[selection[0]]
            chosen_size = size_var.get()

            Terminal.CurrentFontPitch = chosen_size
            Terminal.CurrentFont = (chosen_family, chosen_size)

            # Update the "default" tag to use the new font
            self.TDisplay.tag_configure("default",
                                         font=(chosen_family, chosen_size),
                                         foreground="white",
                                         background="black")

            # Update all existing style tags that use the default font size
            # to use the new font size. This is a simplification — it just
            # updates the base font for all tags that were created.
            for key, tag_name in Terminal._tag_cache.items():
                # Rebuild the font tuple with the new family/size
                old_font = self.TDisplay.tag_cget(tag_name, "font")
                # Parse style info and reconstruct
                self.TDisplay.tag_configure(tag_name,
                    font=(chosen_family, chosen_size))

            # Also update the TInput font
            self.TInput.config(font=(chosen_family, chosen_size, "bold"))

            font_dialog.destroy()

        def cancel_font():
            """Close the dialog without applying changes."""
            font_dialog.destroy()

        # Buttons
        btn_frame = tk.Frame(font_dialog)
        btn_frame.pack(fill=tk.X, padx=5, pady=5)
        tk.Button(btn_frame, text="OK", command=apply_font).pack(side=tk.LEFT, padx=5)
        tk.Button(btn_frame, text="Cancel", command=cancel_font).pack(side=tk.RIGHT, padx=5)

    def ProcessPlayerInput(self):
        """
        This function takes the player's typed input and processes it. First
        the parser is called, then the command text box is cleared. Then the
        parsed command is executed.
        """

        #--------------------------
        # Parse Player's Command(s)
        #--------------------------

        P.AP().GetPlayerInput()
        while P.AP().CommandsList:

            #------------------
            # Clear Command Box
            #------------------

            self.TInput.delete(0, tk.END)

            #-----------------------
            # Handle Pre-Turn Events
            #-----------------------

            Engine.PreTurnHandler()

            #-------------------------------
            # If Command Successfully Parsed
            #-------------------------------

            if P.AP().Parser() == SUCCESS:
                if Engine.TurnHandler() == TURN_ENDS:
                    Engine.AfterTurnHandler()

            #-------------------------------------------------
            # One turn finished, put a paragraph in the output
            #-------------------------------------------------

            Say("~n ")

            #---------------
            # Game Finished?
            #---------------

            if Global.GameState == FINISHED:
                Engine.PostGameWrapUp()
                Terminal.Terminate()

        #---------------------------
        # Display The Command Prompt
        #---------------------------

        Say("~n " + P.AP().Prompt())


#********************************************************************************
#                                  Functions
#

C="""
  These functions must be defined in the module that imports PAWS, Universe,
  and your game to work properly, this has to do with the way Python stores
  variables.
  """

def Restore(FileName):
    """Restore a previously saved game from disk"""

    #---------------------
    # Open Saved Game File
    #---------------------

    try:
        SavedGame = open(FileName+".PSG","rb")
    except:
        Say("You haven't saved a game yet.")
        return FAILURE

    #-----------------------
    # Retrieve Global Object
    #-----------------------

    SavedObject = pickle.load(SavedGame)

    #-------------------------------------------
    # Restore all properties & objects in Global
    #-------------------------------------------

    for attr,value in list(SavedObject.__dict__.items()):
        setattr(Global,attr,value)
        DebugTrace("Restoring "+attr)

    #----------------------
    # Close Saved Game File
    #----------------------

    SavedGame.close()

    #--------------------------------
    # Inform Caller Restore Succeeded
    #--------------------------------

    return SUCCESS

def Save(FileName):
    """Save the game in progress to disk"""

    #-------------------------
    # Erase Old Save Game File
    #-------------------------

    try:
        os.remove(FileName + ".PSG")
    except:
        pass

    #----------
    # Open File
    #----------

    SavedGame = open(FileName+".PSG","wb")

    #-----------------
    # Create PickleJar
    #-----------------

    PickleJar = pickle.Pickler(SavedGame,BINARY_PICKLE)

    #-------------------
    # Save Global Object
    #-------------------

    try:
        PickleJar.dump(Global)
    except:
        print("save error!")

    #----------------------
    # Close Saved Game File
    #----------------------

    SavedGame.close()

    #--------------------------------
    # Inform Caller Restore Succeeded
    #--------------------------------

    return SUCCESS


def TranslateCBExpression(Text=""):
    """
    This function takes a string and translates any valid Python
    expression(s) enclosed within curly braces (the symbols { and }) into
    strings and returns the resulting string to the caller.
    """

    #---------------------------
    # Convert Text If Wrong Type
    #---------------------------

    if type(Text) != type(""): Text = repr(Text)

    #-----------------------
    # Return Text If not CBE
    #-----------------------

    if "{" not in Text or "}" not in Text: return Text

    #-----------------------------------
    # Find { and } Positions Within Text
    #-----------------------------------

    OpenBrace  = Text.find("{")
    CloseBrace = Text.find("}")

    #---------------------
    # Try To Translate CBE
    #---------------------

    try:
        Expr = eval(Text[OpenBrace+1:CloseBrace])
        if type(Expr) != type(""): Expr = repr(Expr)
    except Exception as e:
        Expr = "Invalid CBE '%s' (error: %s)" % (Text[OpenBrace+1:CloseBrace], e)

    #------------------------
    # Replace CBE With Result
    #------------------------

    ReturnValue = Text[:OpenBrace] + Expr + Text[CloseBrace + 1:]

    #------------------------------
    # Handle CBE Resulting From CBE
    #------------------------------

    ReturnValue = TranslateCBExpression(ReturnValue)

    #----------------------
    # Return Translated CBE
    #----------------------

    return ReturnValue

#********************************************************************************
#                             Hook Functions Into Engine
#

C="""
  We have functions (Save, Restore, and CBE Translation) that are vital to
  running your game successfully. The problem is the functions are defined
  here (in this file), but are needed there (in PAWS, Universe, and your
  game).

  PAWS contains the game engine, and is visible to every other file. The
  answer then is to "hook" our functions into the game engine. Once that's
  done the functions are visible to every file--including PAWS itself.

  This technique is used a great deal in PAWS, it's called "indirect
  referencing" and it's one of the things that makes Python such a simple
  and powerful language.
  """

Engine.RestoreFunction = Restore
Engine.SaveFunction = Save
Engine.XlateCBEFunction = TranslateCBExpression

#--- Set Play Module Version

C="""
  PlayModuleVersion is this module's version, which is valuable information
  since you pretty much want to keep the Engine, world library, and play
  module at the SAME version to avoid problems. While every effort is made
  to keep the three programs backwardly compatible, it's not always possible
  to do so.
  """

Global.PlayModuleVersion = "2.1"

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#                             END OF TERMINAL SUPPORT CODE                      %
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%